
# Linker Config
#
# This file contains symbols and their relative address in the botw main module
# 
# "manual" and "auto" are used to generate linker script
# "auto" are the ones found by the build tool from the symbol listing
# "unused" are not used to generate linker script
#
# Note that this is not parsed as a standard yaml file. Comments work, but many yaml features don't



auto:
  0x00b18864: _ZN4sead15CriticalSectionC1Ev 
  0x00b1891c: _ZN4sead15CriticalSectionD1Ev 
  0x00b1898c: _ZN4sead15CriticalSection4lockEv 
  0x00b1899c: _ZN4sead15CriticalSection6unlockEv 
  0x00b1f868: _ZN4sead10TextWriter6printfEPKcz 

manual:

unused:
